### ISSUE TITLE
Bibliografia

### ISSUE THREAD

**Issue by 7IMING** [7IMING/Dicorato-TILE23#1]
@grammaton Salve Maestro, ho terminato la tesi ma la bibliografia non viene stampata nel pdf, sicuramente c'è qualche problema in latex a causa di qualche mia mancanza tecnica. Può aiutarmi a risolvere questo problema? La ringrazio

[https://7iming-stunning-broccoli-44vvp99pq963jw46.github.dev](url)

**Comment by grammaton** [comment]
era piena di errori.
devi farla girare con biber.
